### ISSUE TITLE
Adjust Application Plumbing to K8up

### ISSUE THREAD

**Issue by tobru** [vshn/crossplane-service-broker#21]
## Context

In [K8up](https://github.com/vshn/k8up) we put a lot of effort in the plumbing of the operator. Adjust this repository to adhere to the plumbing of K8up. This includes:

* GitHub issue templates
* GitHub actions
* Release workflow incl. automated Changelog generation
* Plumbing for testing

Do the same in https://github.com/vshn/swisscom-service-broker

**Comment by mweibel** [comment]
@tobru k8up pushes to quay.io additionally to docker.io - should we do that here as well?

**Comment by tobru** [comment]
Yes, that would make sense.
